server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mtask
    username: postgres
    password: 123321

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect